// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: frame_stats_message.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_frame_5fstats_5fmessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_frame_5fstats_5fmessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_frame_5fstats_5fmessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_frame_5fstats_5fmessage_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_frame_5fstats_5fmessage_2eproto;
namespace PhysicsTelemetry {
class FrameStatsMessage;
class FrameStatsMessageDefaultTypeInternal;
extern FrameStatsMessageDefaultTypeInternal _FrameStatsMessage_default_instance_;
}  // namespace PhysicsTelemetry
PROTOBUF_NAMESPACE_OPEN
template<> ::PhysicsTelemetry::FrameStatsMessage* Arena::CreateMaybeMessage<::PhysicsTelemetry::FrameStatsMessage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace PhysicsTelemetry {

// ===================================================================

class FrameStatsMessage :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PhysicsTelemetry.FrameStatsMessage) */ {
 public:
  FrameStatsMessage();
  virtual ~FrameStatsMessage();

  FrameStatsMessage(const FrameStatsMessage& from);
  FrameStatsMessage(FrameStatsMessage&& from) noexcept
    : FrameStatsMessage() {
    *this = ::std::move(from);
  }

  inline FrameStatsMessage& operator=(const FrameStatsMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline FrameStatsMessage& operator=(FrameStatsMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const FrameStatsMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FrameStatsMessage* internal_default_instance() {
    return reinterpret_cast<const FrameStatsMessage*>(
               &_FrameStatsMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FrameStatsMessage& a, FrameStatsMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(FrameStatsMessage* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline FrameStatsMessage* New() const final {
    return CreateMaybeMessage<FrameStatsMessage>(nullptr);
  }

  FrameStatsMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<FrameStatsMessage>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const FrameStatsMessage& from);
  void MergeFrom(const FrameStatsMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FrameStatsMessage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PhysicsTelemetry.FrameStatsMessage";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_frame_5fstats_5fmessage_2eproto);
    return ::descriptor_table_frame_5fstats_5fmessage_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFrameIdFieldNumber = 1,
    kConsumedFrameTimeFieldNumber = 2,
    kFrameProcessingTimeFieldNumber = 3,
  };
  // int32 frameId = 1;
  void clear_frameid();
  ::PROTOBUF_NAMESPACE_ID::int32 frameid() const;
  void set_frameid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_frameid() const;
  void _internal_set_frameid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // float consumedFrameTime = 2;
  void clear_consumedframetime();
  float consumedframetime() const;
  void set_consumedframetime(float value);
  private:
  float _internal_consumedframetime() const;
  void _internal_set_consumedframetime(float value);
  public:

  // float frameProcessingTime = 3;
  void clear_frameprocessingtime();
  float frameprocessingtime() const;
  void set_frameprocessingtime(float value);
  private:
  float _internal_frameprocessingtime() const;
  void _internal_set_frameprocessingtime(float value);
  public:

  // @@protoc_insertion_point(class_scope:PhysicsTelemetry.FrameStatsMessage)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::int32 frameid_;
  float consumedframetime_;
  float frameprocessingtime_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_frame_5fstats_5fmessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FrameStatsMessage

// int32 frameId = 1;
inline void FrameStatsMessage::clear_frameid() {
  frameid_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 FrameStatsMessage::_internal_frameid() const {
  return frameid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 FrameStatsMessage::frameid() const {
  // @@protoc_insertion_point(field_get:PhysicsTelemetry.FrameStatsMessage.frameId)
  return _internal_frameid();
}
inline void FrameStatsMessage::_internal_set_frameid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  frameid_ = value;
}
inline void FrameStatsMessage::set_frameid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_frameid(value);
  // @@protoc_insertion_point(field_set:PhysicsTelemetry.FrameStatsMessage.frameId)
}

// float consumedFrameTime = 2;
inline void FrameStatsMessage::clear_consumedframetime() {
  consumedframetime_ = 0;
}
inline float FrameStatsMessage::_internal_consumedframetime() const {
  return consumedframetime_;
}
inline float FrameStatsMessage::consumedframetime() const {
  // @@protoc_insertion_point(field_get:PhysicsTelemetry.FrameStatsMessage.consumedFrameTime)
  return _internal_consumedframetime();
}
inline void FrameStatsMessage::_internal_set_consumedframetime(float value) {
  
  consumedframetime_ = value;
}
inline void FrameStatsMessage::set_consumedframetime(float value) {
  _internal_set_consumedframetime(value);
  // @@protoc_insertion_point(field_set:PhysicsTelemetry.FrameStatsMessage.consumedFrameTime)
}

// float frameProcessingTime = 3;
inline void FrameStatsMessage::clear_frameprocessingtime() {
  frameprocessingtime_ = 0;
}
inline float FrameStatsMessage::_internal_frameprocessingtime() const {
  return frameprocessingtime_;
}
inline float FrameStatsMessage::frameprocessingtime() const {
  // @@protoc_insertion_point(field_get:PhysicsTelemetry.FrameStatsMessage.frameProcessingTime)
  return _internal_frameprocessingtime();
}
inline void FrameStatsMessage::_internal_set_frameprocessingtime(float value) {
  
  frameprocessingtime_ = value;
}
inline void FrameStatsMessage::set_frameprocessingtime(float value) {
  _internal_set_frameprocessingtime(value);
  // @@protoc_insertion_point(field_set:PhysicsTelemetry.FrameStatsMessage.frameProcessingTime)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace PhysicsTelemetry

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_frame_5fstats_5fmessage_2eproto
